### ISSUE TITLE
feat: Support ailwind 4 (without @nuxtjs/tailwindcss)

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/og-image#359]
### 🆒 Your use case

As of right now, there is no`@nuxtjs/tailwindcss` module for Tailwind 4 because Tailwind now has first class Vite support:

nuxt.config.ts:
```
vite: {
    plugins: [tailwindcss()],
  },
css: ['~/assets/css/main.css'],
```

Therefor when using Tailwind 4, the `og-image` module seems to not load the Tailwind config anymore, which actually doesnt exist, instead only a css file is loaded and used for configuration, e.g.:

assets/css/main.css:
```css
@import "tailwindcss";

@theme {
    --font-sans: 'Inter', sans-serif;
    --font-serif: 'Merriweather', sans-serif;
}
```

But how to tell `og-image` to load this css file, too?

### 🆕 The solution you'd like

- New prop in nuxt.config to tell to load a css file (that can contain Tailwind config)
- Update docs
